name: One Damn Pixel!
tagline: Two dudes writing code.
location: Milwaukee, WI
twitter: http://twitter.com/OneDamnPixel
github: https://github.com/OneDamnPixel
markdown: redcarpet
pygments: false
permalink: /:year/:month/:title
